In [342]:
import pandas as pd
import numpy as np

In [343]:
df=pd.read_csv('Customer_Journey_Data.csv')

In [344]:
df

,CustomerID,Month Of Interaction,New/Old Customer,Referral sources,Clothing Section,Journey Stage,Touchpoints,Actions,Outcomes,Sales Campaign,Feedback Rating,Channels
0,1,March,No,Friends/Family,Men,Awareness,Website,Viewed Product,Continued Browsing,End of Season Sale,8,Online
1,2,January,No,Social Media Influencer,Men,Purchase,Website,Made Purchase,Purchased,Winter Collection,2,Online
2,3,February,Yes,Friends/Family,Men,Purchase,E-Commerce,Made Purchase,Purchased,End of Season Sale,2,Online
3,4,January,Yes,Friends/Family,Men,Awareness,Website,Viewed Product,Continued Browsing,Winter Collection,9,Online
4,5,January,Yes,Friends/Family,Men,Purchase,Social Media,Added to Cart,Purchased,Winter Collection,5,Online
...,...,...,...,...,...,...,...,...,...,...,...,...
245,246,March,No,Social Media Influencer,Kids,Consideration,Social Media,Added to Cart,Continued Browsing,End of Season Sale,8,Online
246,247,January,No,Social Media Influencer,Women,Consideration,In-Store,Added to Cart,Continued Browsing,Winter Collection,3,In-Person
247,248,April,No,Advertisement,Women,Consideration,Website,Added to Cart,Continued Browsing,New Arrivals,8,Online
248,249,March,No,Advertisement,Men,Awareness,Social Media,Viewed Product,Continued Browsing,New Arrivals,4,Online
249,250,April,Yes,Social Media Influencer,Men,Consideration,Social Media,Added to Cart,Continued Browsing,New Arrivals,8,Online

In [345]:
data=pd.read_csv('product_data (Recovered).csv')

In [346]:
data

,CustomerID,ProductID,Product Name,Product Category,Clothing Section,Sales Campaign,Discount Applied?,Total Amount (in Rs)
0,2,1001,Tshirt,Topwear,Men,Winter Collection,Yes,690
1,3,1002,Tshirt,Topwear,Men,End of Season Sale,No,2845
2,5,1003,Shoes,Footwear,Men,Winter Collection,Yes,3325
3,6,1004,Co-ord Sets,Topwear,Men,End of Season Sale,Yes,2430
4,7,1005,Shorts,Bottomwear,Men,Winter Collection,No,1145
...,...,...,...,...,...,...,...,...
111,220,1112,Shirt,Topwear,Men,New Arrivals,Yes,3935
112,221,1113,Shirt,Topwear,Women,New Arrivals,Yes,1625
113,222,1114,Shoes,Footwear,Men,Summer Collection,Yes,3620
114,223,1115,Shirt,Topwear,Women,End of Season Sale,No,1485
115,225,1116,Shoes,Footwear,Kids,End of Season Sale,No,2945

In [347]:
data2=pd.merge(df,data,how='outer')

In [348]:
data2

,CustomerID,Month Of Interaction,New/Old Customer,Referral sources,Clothing Section,Journey Stage,Touchpoints,Actions,Outcomes,Sales Campaign,Feedback Rating,Channels,ProductID,Product Name,Product Category,Discount Applied?,Total Amount (in Rs)
0,1,March,No,Friends/Family,Men,Awareness,Website,Viewed Product,Continued Browsing,End of Season Sale,8.0,Online,NaN,NaN,NaN,NaN,NaN
1,2,January,No,Social Media Influencer,Men,Purchase,Website,Made Purchase,Purchased,Winter Collection,2.0,Online,1001.0,Tshirt,Topwear,Yes,690.0
2,3,February,Yes,Friends/Family,Men,Purchase,E-Commerce,Made Purchase,Purchased,End of Season Sale,2.0,Online,1002.0,Tshirt,Topwear,No,2845.0
3,4,January,Yes,Friends/Family,Men,Awareness,Website,Viewed Product,Continued Browsing,Winter Collection,9.0,Online,NaN,NaN,NaN,NaN,NaN
4,5,January,Yes,Friends/Family,Men,Purchase,Social Media,Added to Cart,Purchased,Winter Collection,5.0,Online,1003.0,Shoes,Footwear,Yes,3325.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,247,January,No,Social Media Influencer,Women,Consideration,In-Store,Added to Cart,Continued Browsing,Winter Collection,3.0,In-Person,NaN,NaN,NaN,NaN,NaN
247,248,April,No,Advertisement,Women,Consideration,Website,Added to Cart,Continued Browsing,New Arrivals,8.0,Online,NaN,NaN,NaN,NaN,NaN
248,249,March,No,Advertisement,Men,Awareness,Social Media,Viewed Product,Continued Browsing,New Arrivals,4.0,Online,NaN,NaN,NaN,NaN,NaN
249,250,April,Yes,Social Media Influencer,Men,Consideration,Social Media,Added to Cart,Continued Browsing,New Arrivals,8.0,Online,NaN,NaN,NaN,NaN,NaN
250,64,NaN,NaN,NaN,Women,NaN,NaN,NaN,NaN,End of Season Sale,NaN,NaN,1043.0,Cap,Accessories,Yes,1725.0

In [349]:
data2['New/Old Customer'].replace('Yes','New Customer',inplace=True)
data2['New/Old Customer'].replace('No','Old Customer',inplace=True)

In [350]:
data2

,CustomerID,Month Of Interaction,New/Old Customer,Referral sources,Clothing Section,Journey Stage,Touchpoints,Actions,Outcomes,Sales Campaign,Feedback Rating,Channels,ProductID,Product Name,Product Category,Discount Applied?,Total Amount (in Rs)
0,1,March,Old Customer,Friends/Family,Men,Awareness,Website,Viewed Product,Continued Browsing,End of Season Sale,8.0,Online,NaN,NaN,NaN,NaN,NaN
1,2,January,Old Customer,Social Media Influencer,Men,Purchase,Website,Made Purchase,Purchased,Winter Collection,2.0,Online,1001.0,Tshirt,Topwear,Yes,690.0
2,3,February,New Customer,Friends/Family,Men,Purchase,E-Commerce,Made Purchase,Purchased,End of Season Sale,2.0,Online,1002.0,Tshirt,Topwear,No,2845.0
3,4,January,New Customer,Friends/Family,Men,Awareness,Website,Viewed Product,Continued Browsing,Winter Collection,9.0,Online,NaN,NaN,NaN,NaN,NaN
4,5,January,New Customer,Friends/Family,Men,Purchase,Social Media,Added to Cart,Purchased,Winter Collection,5.0,Online,1003.0,Shoes,Footwear,Yes,3325.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,247,January,Old Customer,Social Media Influencer,Women,Consideration,In-Store,Added to Cart,Continued Browsing,Winter Collection,3.0,In-Person,NaN,NaN,NaN,NaN,NaN
247,248,April,Old Customer,Advertisement,Women,Consideration,Website,Added to Cart,Continued Browsing,New Arrivals,8.0,Online,NaN,NaN,NaN,NaN,NaN
248,249,March,Old Customer,Advertisement,Men,Awareness,Social Media,Viewed Product,Continued Browsing,New Arrivals,4.0,Online,NaN,NaN,NaN,NaN,NaN
249,250,April,New Customer,Social Media Influencer,Men,Consideration,Social Media,Added to Cart,Continued Browsing,New Arrivals,8.0,Online,NaN,NaN,NaN,NaN,NaN
250,64,NaN,NaN,NaN,Women,NaN,NaN,NaN,NaN,End of Season Sale,NaN,NaN,1043.0,Cap,Accessories,Yes,1725.0

#### dropping unnecessary columns

In [351]:
data2.drop(columns=["Discount Applied?"],inplace=True)

#### saving the final cleaned file to csv

In [352]:
data2.to_csv('cleaned_data.csv',index=False)